# Generated by Django 6.0.2 on 2026-05-05 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteRequestDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('route_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.routerequest')),
            ],
        ),
        migrations.CreateModel(
            name='RouteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField()),
                ('path', models.JSONField(default=list)),
                ('algorithm_used', models.CharField(choices=[('DIJKSTRA', 'Dijkstra (Shortest Path)'), ('A_STAR', 'A* (Heuristic Search)')], default='DIJKSTRA', max_length=8)),
                ('execution_time', models.DurationField()),
                ('route_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routes.routerequest')),
            ],
        ),
    ]
