# Generated by Django 6.0.2 on 2026-04-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='RouteRequestDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('route_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.routerequest')),
            ],
        ),
        migrations.CreateModel(
            name='RouteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField()),
                ('algorithm_used', models.CharField(choices=[('DIJKSTRA', 'Dijkstra (Shortest Path)'), ('A_STAR', 'A* (Heuristic Search)')], default='DIJKSTRA', max_length=8)),
                ('execution_time', models.DurationField()),
                ('route_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routes.routerequest')),
            ],
        ),
    ]
