# Generated by Django 6.0.2 on 2026-05-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeresult',
            name='algorithm_used',
            field=models.CharField(choices=[('DIJKSTRA', 'Dijkstra (Shortest Path)'), ('A_STAR', 'A* (Heuristic Search)'), ('TSP_APPROX', 'Tsp Approx')], default='DIJKSTRA', max_length=10),
        ),
    ]
