# Generated by Django 6.0.2 on 2026-04-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_routerequest_timestamp_alter_routerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeresult',
            name='path',
            field=models.JSONField(default=list),
        ),
    ]
